version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: coffeetica
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coffeetica-network
    restart: unless-stopped

  backend:
    build:
      context: ./coffeetica-backend
    container_name: backend

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - coffeetica-network
    restart: unless-stopped
  frontend:
    build:
      context: ./coffeetica-frontend
      args:
        - VITE_API_BASE_URL=https://api.coffeetica.eu/api
    container_name: frontend
    environment:
      - VITE_API_BASE_URL=https://api.coffeetica.eu/api
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - coffeetica-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  coffeetica-network:
    driver: bridge

      